
# docker-compose.yml
version: '3.8'

services:
  pdf-summarizer-api:
    build: .
    ports:
      - "7860:7860"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MCP_SERVER_URL=http://mcp-server:8080
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/app/uploads
      - ./summaries:/app/summaries
      - ./embeddings:/app/embeddings
    depends_on:
      - redis
      - mcp-server

  mcp-server:
    image: anthropic/mcp-server:latest
    ports:
      - "8080:8080"
    environment:
      - MODEL_CONFIG_PATH=/app/config/models.json
    volumes:
      - ./mcp-config:/app/config

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - pdf-summarizer-api

  worker:
    build: .
    command: celery -A main.celery worker --loglevel=info
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./uploads:/app/uploads
      - ./summaries:/app/summaries
      - ./embeddings:/app/embeddings
    depends_on:
      - redis

volumes:
  redis_data:


